id: P010604
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:08.077206
source_metadata:
  id: bdr:W1KG15996
  title: གྲུབ་དབང་སྦྱིན་པ་ནོར་བུའི་རང་རྣམ།
  author: ''
  volumes:
    39ebf538b7ea4942874186546120994b:
      image_group_id: I1KG16000
      title: ''
      volume_number: 1
      total_pages: 530
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
