id: IF1217B2B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T07:30:01+00:00'
last_modified: '2022-06-08T16:11:05.194141+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15996
  title: གྲུབ་དབང་སྦྱིན་པ་ནོར་བུའི་རང་རྣམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E641:
      image_group_id: I1KG16000
      title: ''
      total_pages: 530
      order: 1
      base_file: E641.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
